### ISSUE TITLE
Interface (site): broken links on taxonomy & criteria pages

### ISSUE THREAD

**Issue by sadielbartholomew** [rseng/rseng#25]
* Rseng version: n/a [concerns online interface]
* Python version: n/a [ditto]
* Operating System: Linux Mint 19.2*

*where the interface was viewed on Chrome Version 80.0.3987.149 (Official Build) (64-bit), though both pieces of info are probably irrelevant.

### Description

Hi, you may be aware of this but the Issue Tracker suggest not. I've noticed there are a set of broken links on the interface/site served at `https://rseng.github.io/rseng/`. (I otherwise would have put a PR in since it is probably simple to fix them, but it wasn't clear to me where these bad links are originated from in the source here or in another `rseng` respository.)

Specifically, of concern are the links against the buttons with the GitHub icon by the titles for the pages `https://rseng.github.io/rseng/criteria/*/` and `https://rseng.github.io/rseng/taxonomy/*/` which all lead (me at least) to a 404 error page, e.g. after being directed to [https://github.com/rseng/rseng/blob/master/_taxonomy/RSE-taxonomy-analysis.md](https://github.com/rseng/rseng/blob/master/_taxonomy/RSE-taxonomy-analysis.md).

### What I Did

1. Navigate through the site from the main page `https://rseng.github.io/rseng/`, via the 'browse' menu button to `https://rseng.github.io/rseng/tag/`.
2. Click on any of the criteria or taxonomy items listed there to go to the dedicated page for that item.
3. Click the link against the GitHub icon by the page title, which at least for me always led to a 404 error page.

**Comment by vsoch** [comment]
Ah, thanks for pointing this out! The pages are now hosted on `gh-pages` so "master" just needs to be changed to "gh-pages", e.g., https://github.com/rseng/rseng/blob/gh-pages/_criteria/RSE-absence.md. Do you have bandwidth to do a PR - the file is here -> https://github.com/rseng/rseng/blob/gh-pages/_includes/appheader.html#L15. Let me know if you do or not, I can definitely also quickly make the change.

**Comment by sadielbartholomew** [comment]
Hi @vsoch, thanks for the quick reply. Sure thing, I'll put up a PR later today. Thanks for the tip about the location. 🙂

**Comment by vsoch** [comment]
Fixed by #27
